--ALTER DATABASE mockZooManagement
--SET ALLOW_SNAPSHOT_ISOLATION ON;

USE mockZooManagement;

--A1
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
BEGIN TRANSACTION;
SELECT StaffID, FirstName, LastName, Role
FROM Staff
WHERE StaffID = 7;

--B1
BEGIN TRANSACTION;
    UPDATE Staff SET Role = 'Director' WHERE StaffID = 7;
COMMIT TRANSACTION;

--A2
UPDATE Staff SET Role = 'Keeper' WHERE StaffID = 7;
COMMIT TRANSACTION;